version: '3'
services:
  publisher:
    build: "cmd/publisher"
    image: publisher
    depends_on: 
      - redis
  sumfinder:
    build: "cmd/subscriber/sumfinder"
    image: sumfinder
    depends_on: 
      - redis
  redis:
    image: "redis:alpine"